on:
  push:
    branches:
      - release
      - next

name: Publish

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: bahmutov/npm-install@v1
      - run: npm install -g yarn && npm install -g pnpm
      - run: yarn lint
      - run: yarn type-check
      - run: yarn test

  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{secrets.SSH_PRIVATE_KEY}}
      - name: Prepare repository
        run: git fetch --unshallow --tags
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: bahmutov/npm-install@v1
      - run: yarn install
      - name: Deploy
        run: |
          yarn deploy
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          SLACK_WEBHOOK: ${{secrets.NPM_SLACK_WEBHOOK}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
