on:
  push:
    branches:
      - release
      - next

name: Publish

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install -g yarn
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run type-check
      - run: pnpm run test

  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{secrets.SSH_PRIVATE_KEY}}
      - name: Prepare repository
        run: git fetch --unshallow --tags
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'pnpm'
      - run: pnpm install
      - name: Deploy
        run: |
          pnpm run deploy
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          SLACK_WEBHOOK_URL: ${{secrets.NPM_SLACK_WEBHOOK}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
